version: "3"
services:
    nginx-proxy:
        container_name: nginx-proxy
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
